### ISSUE TITLE
injected array instance fails test for instanceof Array

### ISSUE THREAD

**Issue by ghost** [felixge/node-sandboxed-module#13]
I found a defect in latest version that when i inject an array and it will not be an instance of Array any more, reproduce with below code

<pre><code>
// lib.js
module.exports = {
    'a' : 1,
    'b' : [1,2,3]
}

// target.js
var lib = require('./lib')
    , assert = require('chai').assert

module.exports.test = function(){
    return lib.a
}

module.exports.test2 = function(){
    console.log(lib.b)
    console.log(lib.b instanceof Array)
        // should be true
    return lib.b instanceof Array
}

// test.js, with mocha 
describe('SandboxedModule', function() {
  it('should return true, for an array', function() {
    var target = SandboxedModule.require('./helper/target', {
      requires : {
        './lib' : {
          'b' : [9, 8, 7]
        }
      }
    })
    assert.isTrue(target.test2());
  })
});

</code></pre>

**Comment by chriswininger** [comment]
Don't know what their source is like, but I've observed the following frustrating behavior with node vm

function _test(grr) { console.log('!!! grr: ' +  (grr instanceof Array)); }

 _test([])
=> true

vm.runInNewContext('(function() { _test([]) })()', { console: console, _test: _test })
=> false

vm.runInNewContext('(function() { _test([]) })()', { console: console, _test: _test, Array: Array })
=> false

In this case Array.isArray will return true, just as mentioned here
