### ISSUE TITLE
Istanbul source transformer and node_modules

### ISSUE THREAD

**Issue by elliotstokes** [felixge/node-sandboxed-module#39]
I have been using the Istanbul source transformer and it works great. I have a small issue though that it doesn't ignore the node_modules folder and am getting code_coverage for these (i.e. underscore). I have written a work-around to get around this locally. Could we get this or someway to ignore files and paths included?

Will happily send you a push request if you think its worth it.

**Comment by selaux** [comment]
I have the same issue here, any chance for a pull request?

**Comment by domenic** [comment]
You should be able to use `sourceTransformersSingleOnly` instead of `sourceTransformers` to get this behavior. Let me know if that works; if it doesn't then we have a bug.

**Comment by selaux** [comment]
Yep, works when using ```sourceTransformersSingleOnly```.

**Comment by domenic** [comment]
Awesome!

**Comment by ccprog** [comment]
Could you be so kind to document this option? Finding it in a closed issue is not that ideal...

**Comment by ccprog** [comment]
I'm too quick today. After more testing, I do not understand how this is supposed to work. Consider this jasmine clause:
```js
    var stdin, utils, spawn, iconize;
    var spawnLineFn, normalizeCallbacks = {};

    beforeEach(function () {
        stdin = {
            write: jasmine.createSpy('write')
        };
        utils = {
            normalize: function (fn, callback) {
                normalizeCallbacks[fn] = callback;
            },
            handleErr: jasmine.createSpy('handleErr')
        };
        spyOn(utils, 'normalize').and.callThrough();
        spawn = jasmine.createSpy('spawn')
                .and.callFake(function (cmd, lineFn) {
            spawnLineFn = lineFn;
            return stdin;
        });
        iconize = SandboxedModule.require('../../lib/iconize-png.js', {
            requires: { './utils': utils, './spawn': spawn },
            globals: { 'console': { log: () => {} } }
        });
    });
```
The tested module has an additional `require('async')`, it will be included in coverage if used like this.

Adding `sourceTransformersSingleOnly: true` does not change this, it is still in the results.

Adding `singleOnly: true` leads to the spec failing, because the mocks are not available.

Requiring async in the spec and adding it to the requires:
```js
var async = require('async');
//...
            requires: { 'async': async, './utils': utils, './spawn': spawn },
```
excludes async from coverage.
