### ISSUE TITLE
[help needed] [discussion] [usage question] accessing module private methods 

### ISSUE THREAD

**Issue by hellboy81** [felixge/node-sandboxed-module#54]
Is there possible to access private method with `sandboxed-module`?

```js
function myPrivateMethod() {
}

module.exports.init = function (...) {
  myPrivateMethod()
}
```

i.e:

- read access to test `myPrivateMethod` in `SUT`
- write access to stub `myPrivateMethod` in `SUT`

**Comment by domenic** [comment]
There is not. I don't even know how you would do that in JavaScript.

**Comment by hellboy81** [comment]
>you would do that in JavaScript.

with `rewire` you can do it

**Comment by domenic** [comment]
Cool! Then I'd suggest using rewire.
